using UnityEngine;

namespace MuriPNG.Audio
{
    /// <summary>
    /// This class represents the settings of an audio clip.
    /// </summary>
    /// <remarks>
    /// It contains the loop flag, the play on awake flag, the mute flag, the ignore effects flag, the ignore listener effects flag, the ignore reverb zone flag, the spatialize flag, the priority, the volume, the pitch, the pan stereo, the spacial blend, the reverb zone mix, the doppler level, the spread, the roll off mode, the minimum distance, and the maximum distance.
    /// </remarks>
    [CreateAssetMenu(fileName = "Sound Settings", menuName = "Sound Manager/Create new Sound Settings")]
    public class SoundSettings : ScriptableObject
    {
        [Tooltip("Is the audio clip in loop?")]
        public bool loop;
        [Tooltip("If set to true, the audio source will start playing automatically when created.")]
        public bool playOnAwake;
        [Tooltip("If the sound is muted or not")]
        public bool mute;
        [Tooltip("Ignore effects (applied from filter components or listener global filters).")]
        public bool ignoreEffects;
        [Tooltip("When set, global effects on the AudioListener will not be applied to the audio signal generated by the AudioSource. Does not apply if the AudioSource is playing in an AudioMixer group.")]
        public bool ignoreListenerEffects;
        [Tooltip("When set, does not route the signal of an AudioSource to the global reverb associated with the reverb zones.")]
        public bool ignoreReverbZone;
        [Tooltip("Enables or disables spatialization.")]
        public bool spatialize;
        [Tooltip("Defines the priority of the AudioSource.")]
        [Range(0f, 256f)] public int priority = 128;
        [Tooltip("The volume of the audio source (0.0 to 1.0).")]
        [Range(0f, 1f)] public float volume = 1f;
        [Tooltip("The pitch of the audio source.")]
        [Range(.1f, 3f)] public float pitch = 1f;
        [Tooltip("Shifts a stereo sound (left or right) being played. This only applies to Mono or Stereo sounds.")]
        [Range(-1, 1f)] public float panStereo;
        [Tooltip("Defines how much this AudioSource is affected by 3D spatialization calculations (attenuation, doppler etc). 0.0 makes the sound fully 2D, 1.0 makes the sound fully 3D.")]
        [Range(0f, 1f)] public float spacialBlend;
        [Tooltip("The amount by which the signal of an AudioSource will be mixed into the global reverb associated with the reverb zones.")]
        [Range(0f, 1.1f)] public float reverbZoneMix = 1f;
        [Tooltip("Defines the Doppler scale for this AudioSource.")]
        public float dopplerLevel = 1f;
        [Tooltip("Defines the spread angle (in degrees) of a 3D stereo or multichannel sound in speaker space.")]
        public float spread;
        [Tooltip("Defines how the AudioSource attenuates over distance.")]
        public AudioRolloffMode rollOffMode = AudioRolloffMode.Logarithmic;
        [Tooltip("Within the minimum distance, the AudioSource will stop increasing the volume.")]
        public float minimumDistance = 1f;
        [Tooltip("(Logarithmic rollOff) maximum distance is the distance at which a sound stops attenuating.")]
        public float maximumDistance = 500f;
    }
}