name: Pull Request DevBuild

on: [pull_request]

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: Build de pull request para ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targetPlatform: [StandaloneWindows64]
    steps:
      # Checkout
      - name: Checkout do repositório
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0
          lfs: true

      # Cache
      - uses: actions/cache@v3.2.6
        with:
          path: Library
          key: Library
          restore-keys: Library-

      # Build
      - name: Build project pull request
        uses: game-ci/unity-builder@v2.2.0
        env:
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          unityVersion: 2021.3.17f1
          targetPlatform: ${{ matrix.targetPlatform }}

      # Output
      - uses: actions/upload-artifact@v3.1.2
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}

      - name: Zip build
        run: |
          PR_NAME=$(echo ${{ github.event.pull_request.title }} | tr ' ' '-')
          pushd build/StandaloneWindows64
          zip -r ../../BuildWindows64-$PR_NAME.zip .
          popd

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.TOKEN }}
          files: BuildWindows64-$PR_NAME.zip
          name: Release ${{ github.ref }} ${{ matrix.targetPlatform }}
          tag_name: builds
